### ISSUE TITLE
Error in enconding character

### ISSUE THREAD

**Issue by guihleao** [matakuka/gridsplitter#2]
Hello! I'm having this problem while trying to use the plugin:

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 965: ordinal not in range(128) 

Am I doing anything wrong? Thanks!

**Comment by matakuka** [comment]
As a first thought: 
This seems like an old python 2.7 bug that file paths/names are not allowed non-ascii characters (on Windows systems). Until now, I could not find a direct workaround for this. If it is this issue, it can only be resolved by switching to python3, which QGIS doesn't support yet (this will change in QGIS 3.0).

If it is *something else* than file/path name, I could use the traceback (the 10 or so lines produced by the error).

**Comment by guihleao** [comment]
Oh you're totally right, I changed the path of the files and now it worked great. Thanks!
